### ISSUE TITLE
Some damn documentation was too difficult?

### ISSUE THREAD

**Issue by Porkechebure** [rogerfar/RD.NET#1]
Write some damn docs when you do a lib.
Readme is:
Hey var client = nre RdNetClient(), that's it!!!!

**Comment by rogerfar** [comment]
Ok thanks asshole

**Comment by rogerfar** [comment]
It's LITERALLY in the README:
![image](https://user-images.githubusercontent.com/1142915/143895445-2260abbe-8fdd-417d-b2c9-bb64bd8f6387.png)

**Comment by Porkechebure** [comment]
> It's LITERALLY in the README: ![image](https://user-images.githubusercontent.com/1142915/143895445-2260abbe-8fdd-417d-b2c9-bb64bd8f6387.png)

IT'S LITERALLY NOT!

YOU ARE JUST SHOWING HOW TO INITIALIZE CLIENT AND 2 AUTH OPTIONS: TOKEN AND OAUTH.

ALL THE REST IS MISSING AND YOU KNOW IT. Don't play stupid and write some damn docs
