### ISSUE TITLE
Getting Available Files Method

### ISSUE THREAD

**Issue by yaga36** [rogerfar/RD.NET#3]
Hello,

I am trying to use the torrents.GetAvailableFiles method and looking at the RD api documentation I am meant to pass in the info hash of a torrent. I am extracting this from a magnet link and passing it though as the Id parameter but I keep getting a ***RDNET.RealDebridException: Unknown method*** error

I have managed to authenticate before calling the method and I have a bearer token when making a request so I think that bit is alright

Can you assist in what I am doing wrong/missing?

Thanks!

**Comment by rogerfar** [comment]
If you look in the test here: https://github.com/rogerfar/RD.NET/blob/6473621c8cfd3fda57301e46e81bcac8e3d0c81a/RDNET.Test/TorrentsTest.cs#L109

Here I am passing the hash of a torrent, this is how RDTClient also uses it, so it should work.
